zp-relayer/package.json
The previous version 1.2.0 formally was on https://github.com/zkBob/zeropool-relayer/commit/7c587c31d7f6e0151403bcaebd43586735bb3f84
=> Bump package version to 1.2.1

zp-relayer/endpoints.ts, zp-relayer/validation/validation.ts
=> Add merkle root index validation

zp-relayer/abi/pool-abi.json, zp-relayer/pool.ts
Update ABI for pool contract. This changes will not break current functionality. Limits checks are performed using `getLimitsFor` contract function which returns corresponding user's limits:
https://github.com/zkBob/zeropool-relayer/blob/999efcc15757204c37758407130eaa9e4b45d1a9/zp-relayer/validateTx.ts#L229-L230
Added new field `tier` in response for `/limits` endpoint. Now, it has the following structure:
```
{
deposit: {
singleOperation: string
daylyForAddress: {
total: string
available: string
}
daylyForAll: {
total: string
available: string
}
poolLimit: {
total: string
available: string
}
}
withdraw: {
daylyForAll: {
total: string
available: string
}
}
tier: string
}
```
=> Update ZkBobPool ABI

CONFIGURATION.md, yarn.lock, zp-memo-parser/memo.ts, zp-memo-parser/package.json, zp-relayer/config.ts, zp-relayer/init.ts, zp-relayer/package.json, zp-relayer/pool.ts, zp-relayer/queue/sentTxQueue.ts, zp-relayer/services/gas-price/GasPrice.ts, zp-relayer/services/gas-price/types.ts, zp-relayer/state/PoolState.ts, zp-relayer/state/nullifierSet.ts, zp-relayer/state/rootSet.ts, zp-relayer/test/pool.test.ts, zp-relayer/utils/helpers.ts, zp-relayer/utils/redisFields.ts, zp-relayer/utils/web3Errors.ts, zp-relayer/validateTx.ts, zp-relayer/workers/poolTxWorker.ts, zp-relayer/workers/sentTxWorker.ts
Closes #35 
Added assertion for permit deadline when resending a transaction.
https://github.com/zkBob/zeropool-relayer/blob/68e93a906abc45469a7be9f541f04d6c5bb3f728/zp-relayer/workers/sentTxWorker.ts#L137-L140
Closes #49 
Added handling of some client errors when resending a transaction.
https://github.com/zkBob/zeropool-relayer/blob/68e93a906abc45469a7be9f541f04d6c5bb3f728/zp-relayer/workers/sentTxWorker.ts#L177
https://github.com/zkBob/zeropool-relayer/blob/68e93a906abc45469a7be9f541f04d6c5bb3f728/zp-relayer/workers/sentTxWorker.ts#L180
Closes #51 
Gas price is updated if corresponding error was thrown during transaction re-send. Related to #49 
Closes #52 
See #77 
Closes #74 
Implemented proper transaction re-send mechanism. Re-send errors related to gasPrice/nonce are handled. Other …
=> Fix tx resend

zp-relayer/package.json
The major version has been increased since `/proof_tx` API-endpoint is not available starting from #59
=> Bump package version to 2.0.0

zp-relayer/pool.ts, zp-relayer/validateTx.ts
Add fallback function in root validation method.
If root was not found in local cache it will be looked up from Pool contract and saved locally.
=> Add fallback in root lookup method

zp-relayer/endpoints.ts
Fix possible concurrency issue (reported by @EvgenKor).
Because `job.getState` method is asynchronous following scenario is possible:
1. We get the job from queue by id
2. We asynchronously get job's state
3. The state is `completed`
4. Job object that we got in the first step does not contain correct `returnvalue` because it was not in `completed` state at the moment of fetching.
Solution:
If we got `completed` job's state, we need to check job's `returnvalue` and if it is `null` re-fetch the job.
=> Fix possible completed job state issue

zp-relayer/workers/sentTxWorker.ts
* Disable re-processing in case transaction was not mined, but nonce increased
* Add log for root divergence
=> Disable re-processing

yarn.lock, zp-relayer/endpoints.ts, zp-relayer/package.json
Changes:
* `bullmq` introduced a previously requested [feature](https://github.com/taskforcesh/bullmq/issues/1532) for getting job state by job id. Now, we can safely remove job-fallbacks from `/job` endpoint to simplify the logic. All inconsistency checks are still there in case there is some unknown possible race condition.
=> Remove fallback job fetching from /job endpoint

.prettierignore, README.md, yarn.lock, zp-relayer/endpoints.ts, zp-relayer/package.json, zp-relayer/router.ts, zp-relayer/state/PoolState.ts, zp-relayer/test/worker-tests/poolWorker.test.ts, zp-relayer/validation/validation.ts
Changes:
* Add `/siblings` endpoint. It returns hex-encoded left sibling nodes starting from the specified leaf index up to the tree root. Requested index `i` should pass following checks: `i > 0`, `i % 128 = 0`, `i < tree.next_index`, otherwise `400 Bad Request` is returned.
Closes #109 
Depends on https://github.com/zkBob/libzkbob-rs/pull/33
=> Add /siblings endpoint

zp-relayer/config.ts, zp-relayer/services/providers/HttpListProvider.ts, zp-relayer/services/web3.ts, zp-relayer/utils/helpers.ts, zp-relayer/utils/web3.ts, zp-relayer/validateTx.ts, zp-relayer/workers/poolTxWorker.ts
Changes:
* Fix circular dependencies
* Add optional HTTPS URL validation via `RELAYER_REQUIRE_HTTPS` env
=> Add HTTPS URL validation

CONFIGURATION.md, zp-relayer/config.ts, zp-relayer/services/providers/HttpListProvider.ts, zp-relayer/services/web3.ts
Changes:
* Add optional periodic RPC sync check similar to [tokenbridge](https://github.com/omni/tokenbridge/blob/961b12b9f3545830a04044e109762277efcea6ef/oracle/src/services/HttpListProvider.js#L51). Interval can be set via `RELAYER_RPC_SYNC_STATE_CHECK_INTERVAL` env (in milliseconds). If the env is not set sync check is disabled by default.
Closes #46
=> Add optional RPC sync check

zp-relayer/package.json
The major version was increased since there is no backward compatibility anymore -- the endpoints `sendTransaction` and `transactions` were removed as part of #121
=> Bump package version to 3.0.0

zp-relayer/tx/signAndSend.ts
Changes:
* `already known` errors are now considered as a successful send. Fixes possible issue with `RedundantHttpListProvider`.
=> Fix already known error with Redundant provider

zp-relayer/pool.ts
Changes:
* Fix block range for `getEvents`. Example range requests for `BATCH_SIZE=10000`: `(0..9999)`, `(10000..19999)`, `(20000..29999)`. Previously it was: `(0..10000)`, `(10000..20000)`, `(20000..30000)`.
Closes #125
=> Fix events block range

zp-relayer/pool.ts
Changes:
* Hot-fix for sync loop. There was a typo in `fromBlock` variable, so block ranges were incorrect.
=> Fix fromBlock value

CONFIGURATION.md, zp-relayer/config.ts, zp-relayer/test/worker-tests/poolWorker.test.ts, zp-relayer/utils/helpers.ts, zp-relayer/validateTx.ts, zp-relayer/workers/poolTxWorker.ts, zp-relayer/workers/sentTxWorker.ts
Changes:
* Fix a bug, that pool limits for withdrawal transactions were checked for zero address only. Now, limits are requested for the withdrawal address.
* Add screener integration.
Closes #132 
Closes #141
=> Add internal account validation

CONFIGURATION.md, zp-relayer/config.ts, zp-relayer/utils/helpers.ts, zp-relayer/workers/poolTxWorker.ts, zp-relayer/workers/sentTxWorker.ts
Changes:
* Add iteration count to `sentTxWorker`.
* Reduce log level of `Ambiguity detected` errors to warn.
* Reduce log level of `nonce too low` errors to warn (for `sentTxWorker` only).
* Add `SENT_TX_ERROR_THRESHOLD` env. If re-send iteration count is more that this threshold, then corresponding error will be logged.
Closes #136
=> Add iteration count to sent worker; Fix log levels

zp-relayer/services/providers/HttpListProvider.ts
Changes:
* On recently deployed prod release we noticed frequent RPC switches. Added a debug log to know the exact reason of this behaviour.
=> Add debug log for RPC request errors

zp-relayer/pool.ts, zp-relayer/router.ts, zp-relayer/utils/helpers.ts, zp-relayer/utils/web3Errors.ts, zp-relayer/validateTx.ts
Changes:
* Add contract call retry functionality in most critical places. But, there a few questions for discussion. How many times should we retry failed calls? Which interval between retries to choose? For now, 2 retries with 500ms interval is set.
Closes #144 
* Improve error handling. Now, in case of unrecoverable error there will be no pure stack traces in logs, instead it will be wrapped in a json logger message. Also, in such cases server will return code 500 with plain text `Internal server error`, instead of HTML template with the same message.
=> Fix failed contract calls

zp-relayer/router.ts
Changes:
* Fix error handler middleware. Previously, it had incorrect method signature, and treated errors incorrectly.
=> Fix error handler middleware

CONFIGURATION.md, zp-relayer/configs/baseConfig.ts, zp-relayer/services/appLogger.ts, zp-relayer/utils/web3.ts
Changes:
* Fix json log formatting
* Add optional colorize parameter
=> Fix json log formatting

zp-relayer/configs/relayerConfig.ts, zp-relayer/endpoints.ts, zp-relayer/init.ts, zp-relayer/services/fee/DynamicFeeManager.ts, zp-relayer/services/fee/FeeManager.ts, zp-relayer/services/fee/OptimismFeeManager.ts, zp-relayer/services/fee/StaticFeeManager.ts, zp-relayer/test/worker-tests/poolWorker.test.ts
Cache fee options to prevent possible relayer's API abuse and to reduce the number of possible client side errors when `/fee` endpoint internally fails (now, it uses cache). Also, during fee validation stage, relayer will fallback to cached value if fetch function fails.
=> Cache fee options
